name: smoke-ubuntu-linux

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

  # allow to trigger workflow manually
  workflow_dispatch:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test

  linux:
    name: "linux 5.32"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    container:
      image: perl:5.32

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: install prerequisities
        run: |
          cpm --version
          wget https://raw.githubusercontent.com/skaji/cpm/main/cpm > /usr/local/bin/cpm
          cpm --version
      - uses: happy-barney/ci-perl-tester-helpers/cpan-install-build-deps@hpb/actionify
      - uses: happy-barney/ci-perl-tester-helpers/build-dist@hpb/actionify
      - uses: happy-barney/ci-perl-tester-helpers/cpan-install-dist-deps@hpb/actionify
      - uses: happy-barney/ci-perl-tester-helpers/test-dist@hpb/actionify
